// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZRL1RShF-fRao0Mc-vIKEZApDsqTthY',
    appId: '1:248424480878:web:e3930dd6a2292f6687667f',
    messagingSenderId: '248424480878',
    projectId: 'hotels-27a0a',
    authDomain: 'hotels-27a0a.firebaseapp.com',
    storageBucket: 'hotels-27a0a.appspot.com',
    measurementId: 'G-GHTQ2PDXZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZZxnyjXwCbhs-RQecwyBl_oNatWGRDcc',
    appId: '1:248424480878:android:46868f15a51bd05587667f',
    messagingSenderId: '248424480878',
    projectId: 'hotels-27a0a',
    storageBucket: 'hotels-27a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vQczN56omqSJq14jBxemsmpuXOVrMHc',
    appId: '1:248424480878:ios:69ce3a8e3afc189d87667f',
    messagingSenderId: '248424480878',
    projectId: 'hotels-27a0a',
    storageBucket: 'hotels-27a0a.appspot.com',
    iosClientId:
        '248424480878-a347oors7grealj8cndg8vuo3uuv614u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8vQczN56omqSJq14jBxemsmpuXOVrMHc',
    appId: '1:248424480878:ios:093819cc8551562387667f',
    messagingSenderId: '248424480878',
    projectId: 'hotels-27a0a',
    storageBucket: 'hotels-27a0a.appspot.com',
    iosClientId:
        '248424480878-rc43dbc8nlnqh8vkritb9mvfrur1jv52.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotels.RunnerTests',
  );
}
